[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_API_URL = "https://profile-api-playground.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
